on: [push]

jobs:
  
  test_job:
    runs-on: ubuntu-latest
    name: Action basic test job
    
    steps:
    - name: Audit Log Action
      uses: ./
      id: audit-log-action      
      with:
        org: 'octodemo'
    
    - name: Get the output time
      run: echo "The org was ${{ steps.audit-log-action.outputs.org }}"